# Generated by Django 6.0.7 on 2026-07-21 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado / Em Uso'), ('RECUSADO', 'Recusado pelo Administrador'), ('CONCLUIDO', 'Concluído/Devolvido')], default='PENDENTE', max_length=15)),
                ('km_inicial', models.IntegerField(verbose_name='KM inicial')),
                ('km_final', models.IntegerField(blank=True, null=True, verbose_name='KM Final')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo')),
            ],
        ),
    ]
