# Generated by Django 6.0.7 on 2026-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrouso'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
